name: DeathSwap
main: com.rh.deathswap.Main
version: 1.0-alpha
author: RussianHacker
description: This plugin enables you to play the deathswap game that was originally made by SethBling.
commands:
  dsgame:
    usage: "Usage: /<command> [join | leave | start | stop | info]"

